name: Random-Events
version: '1.1'
main: lol.ysmu.randomEvents.RandomEvents
api-version: '1.21'
authors: [ ysmu ]
description: A plugin for random events in Minecraft.
commands:
  triggerRandomEvent: # Change this to match the camel-case format
    description: Triggers a random event
    usage: /triggerRandomEvent
  randomevent:
    description: Reloads the configuration for RandomEvents
    usage: /randomevent reload
    aliases:
      - re
permissions:
  randomevents.use:
    description: Allows triggering random events
    default: op
  randomevents.reload:
    description: Allows reloading the plugin configuration
    default: op
  randomevents.bypass:
    description: Allows bypassing the cooldown for random events
    default: op